### ISSUE TITLE
Can't delete existing job

### ISSUE THREAD

**Issue by bydga** [dcos/metronome#110]
Hi, I've just encountered this error: we have been running one scheduled job for some time (each minute for a week)

and now i wanted to delete the job, however calling DELETE resulted in 
```
curl -v -XDELETE https://metronome.internal/v1/jobs/example-api.production.cron
*   Trying 10.64.12.209...
* Connected to metronome.internal (x.x.x.x) port 443 (#0)
* TLS 1.2 connection using TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: metronome.internal
* Server certificate: xxx
* Server certificate: xxx
> DELETE /v1/jobs/example-api.production.cron HTTP/1.1
> Host: metronome.internal
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Length: 59
< Content-Type: application/json
< Date: Tue, 06 Dec 2016 13:47:24 GMT
<
* Connection #0 to host metronome.internal left intact
{"requestPath":"/v1/jobs/example-api.production.cron"}
```

and in the metronome log i found
```[[31merror[0m] d.m.a.ErrorHandler - Error serving /v1/jobs/example-api.production.cron
mesosphere.marathon.StoreCommandFailedException: Can not delete entity job-runs/example-api.production.cron
	at mesosphere.util.state.zk.ZKStore$$anonfun$exceptionTransform$1.applyOrElse(ZKStore.scala:94)
	at mesosphere.util.state.zk.ZKStore$$anonfun$exceptionTransform$1.applyOrElse(ZKStore.scala:93)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Failure.recover(Try.scala:216)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
Caused by: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /metronome/state/job-runs/example-api.production.cron
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:125)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at com.twitter.zk.AsyncCallbackPromise$class.process(AsyncCallbackPromise.scala:18)
	at com.twitter.zk.UnitCallbackPromise.process(AsyncCallbackPromise.scala:29)
	at com.twitter.zk.UnitCallbackPromise.processResult(AsyncCallbackPromise.scala:31)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:609)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
[[31merror[0m] d.m.j.i.JobSpecPersistenceActor - Repository change failed
mesosphere.marathon.StoreCommandFailedException: Can not delete entity job-runs/example-api.production.cron
	at mesosphere.util.state.zk.ZKStore$$anonfun$exceptionTransform$1.applyOrElse(ZKStore.scala:94)
	at mesosphere.util.state.zk.ZKStore$$anonfun$exceptionTransform$1.applyOrElse(ZKStore.scala:93)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Failure.recover(Try.scala:216)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
Caused by: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /metronome/state/job-runs/example-api.production.cron
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:125)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at com.twitter.zk.AsyncCallbackPromise$class.process(AsyncCallbackPromise.scala:18)
	at com.twitter.zk.UnitCallbackPromise.process(AsyncCallbackPromise.scala:29)
	at com.twitter.zk.UnitCallbackPromise.processResult(AsyncCallbackPromise.scala:31)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:609)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
```

restarting metronome itself (i run it as a marathon application) helped and i could `curl -XDELETE` the job afterwards. I guess there must have happened some de-sync between the zookeeper and the in-memory data in metronome..? Or maybe desync against the mesos.. This job has always run only on a schedule, never as a standalone run (via the POST /run).

**Comment by bydga** [comment]
anyone interested, maybe @aquamatthias?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1653. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
